[project]
name = "imgbytesizer"
version = "0.2.6"
description = "A CLI tool to resize images to a target file size."
keywords = ["image", "resize", "compression", "cli", "optimize"]

authors = [{ name = "pyyupsk", email = "contact@fasu.dev" }]

readme = "README.md"
license = { text = "MIT License" }

requires-python = ">=3.10"

dependencies = [
  "pillow>=12.3.0,<13.0.0",
  "pyfiglet>=1.0.2,<2.0.0",
  "tabulate>=0.9.0,<0.10.0",
]

[project.scripts]
imgbytesizer = "imgbytesizer.main:main"

[dependency-groups]
dev = [
  "flake8>=7.2.0",
  "pytest>=9.0.3",
  "pytest-cov>=6.1.1",
  "requests>=2.33.0",
  "types-requests>=2.32.0.20250515",
  "tomli>=2.2.1",
  "types-tabulate>=0.9.0.20241207",
  "vulture>=2.14",
  "yapf>=0.43.0",
  "tox>=4.26.0",
]

[tool.uv]
package = true

[tool.uv.sources]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/imgbytesizer"]
